"""initial migration: create core_users and core_chat_sessions

Revision ID: 3afb7dc0c8f0
Revises: 
Create Date: 2026-05-15 15:00:06.535005
"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

revision: str = '3afb7dc0c8f0'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('core_users',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('nickname', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_core_users_email'), 'core_users', ['email'], unique=True)
    op.create_table('core_chat_sessions',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('thread_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['core_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_core_chat_sessions_thread_id'), 'core_chat_sessions', ['thread_id'], unique=True)
    op.create_index(op.f('ix_core_chat_sessions_user_id'), 'core_chat_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_core_chat_sessions_user_id'), table_name='core_chat_sessions')
    op.drop_index(op.f('ix_core_chat_sessions_thread_id'), table_name='core_chat_sessions')
    op.drop_table('core_chat_sessions')
    op.drop_index(op.f('ix_core_users_email'), table_name='core_users')
    op.drop_table('core_users')
    # ### end Alembic commands ###
