"""增加用户备注字段

Revision ID: 893acf55ec33
Revises: 3afb7dc0c8f0
Create Date: 2026-05-15 15:28:40.579529
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = '893acf55ec33'
down_revision: Union[str, None] = '3afb7dc0c8f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
